#!/bin/tcsh -f
#  rightsdraw
#  Version: 2.0.1
#  Authors: L. Boch
#
#  Copyritght (C) 2012-2013 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set echo_style = both
echo "content-type: text/plain\n"
set repo = $pdir/www/html/kpr
set this = `basename $0`
if ( $REQUEST_METHOD != "GET" ) then
	echo "400"
	echo "Bad request "
	echo "$this accept only GET"
	exit 99
endif
	

set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut -d'=' -f1- --output-delimiter=' '`
set inquery = `$pdir/bin/clean.querystring $inquery`
set instance = "null"
set folder = "test"
set i = 1
while ( $i < $#inquery )
        if ( "$inquery[$i]" == "folder" ) then
                @ i++
                set folder = "$inquery[$i]"
        else
		echo "400"
		echo "Bad request "
		echo "$this $QUERY_STRING"
                exit 1
        endif
        @ i++
end
set ret = 0
#Sanity check
if ( !( -e "$repo/$folder" ) ) then
	echo "404"
	echo "Not Found "
	echo "$this $repo/$folder"
	exit 2
endif
ls -1 $repo/$folder > $pdir/logs/$this.$$
set ret = $?
if ( $ret ) then
	echo "500"
	echo "Server error "
	echo "$this $ret"
	exit 3
endif
echo "200"
echo "Success"
cat $pdir/logs/$this.$$
exit 0
