#!/bin/tcsh -f
set this = `basename $0`
set echo_style = both
if ( $#argv != 2 ) then
	echo "\n$this Usage:\n$this <username> on|off\n"
	exit 1
endif
if ( -e users/$1 ) then
	if ( $2 == on ) then
		if ( -e users/$1/repo/kpr ) then
			echo "$this nothing to do" 
			exit 0
		else if ( -e users/$1/repo/.kpr ) then
			cd users/$1/repo
			mv .kpr kpr
		else
			cd users/$1/repo
			cp -pr pprights kpr
			rm kpr/* kpr/.tmp/*
		endif
	else if ( $2 == off ) then
		if ( -e users/$1/repo/kpr ) then
			cd users/$1/repo
			mv kpr .kpr
		else
			echo "$this nothing to do" 
			exit 0
		endif
	else
		echo "\n$this Usage:\n$this <username> on|off\n"
		exit 1
	endif
else
	echo "$this unknown user $1"
	exit 2
endif
