#!/bin/tcsh -f
set echo_style = both
set this = `basename $0`
echo "content-type: text/html\n"
set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut -d'=' -f1- --output-delimiter=' '`
set inquery = `$pdir/bin/clean.querystring $inquery`
set username = "default"
set i = 1
while ( $i < $#inquery )
        if ( "$inquery[$i]" == "username" ) then
                @ i++
                set username = "$inquery[$i]"
        else
		echo "400"
		echo "Bad request"
		echo "$this unknown $inquery[$i]"
                exit 1
        endif
        @ i++
end
if ( -er "$pdir/users/$username" ) then
	echo '<html><body style="text-align:center;width:80%">'
	echo '<h2 style="color:#660000">Welcome user <i>'$username'</i></h2>'
#	echo '<h3><a href="'"/rightsdraw2/docs"'"'">Help, info, and docs</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/docs"'"'">Help, info, and docs</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/mco/guiadm"'"'">Rights MCO services</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/query/guiadm"'"'">Rights query services</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/pprights/guiadm"'"'">PPRIGHTS repo</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/mkr/guiadm"'"'">MKR services</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/kpr/guiadm"'"'">KPR services</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/combine/guiadm"'"'">Purchases and Sales services</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/query.local/guiadm"'"'">Local search</a></h3>"
	echo '<h3><a href="'"/cgi-bin/rightsdraw2/$username/config/guiadm"'"'">Settings</a></h3>"
	echo '<p><img src="/rightsdraw2/Logo600x100.png"></p>'
	echo "</body></html>\n"
else
	echo "404"
	echo "Not found"
	echo "$this : User $username unknown"
endif
exit
#
#
